force-app/main/default/objects/Account/fields/Bandeira__c.field-meta.xml
<CustomField>
    <fullName>Bandeira__c</fullName>
    <label>Bandeira</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cod_Canal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KEKO</fullName>
            </value>
            <value>
                <fullName>FIAT</fullName>
            </value>
            <value>
                <fullName>HYUNDAI</fullName>
            </value>
            <value>
                <fullName>FORD</fullName>
            </value>
            <value>
                <fullName>RENAULT</fullName>
            </value>
            <value>
                <fullName>PEUGEOT</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>HONDA</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>VOLKS</fullName>
            </value>
            <value>
                <fullName>NISSAN</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MERCEDES</fullName>
            </value>
            <value>
                <fullName>JEEP/RAM</fullName>
            </value>
            <value>
                <fullName>AGRALE</fullName>
                <isActive>false</isActive>
                <label>AGRALE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segmento__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER ME</fullName>
            </value>
            <value>
                <fullName>KEKO USA</fullName>
            </value>
            <value>
                <fullName>AFTER MI</fullName>
            </value>
            <value>
                <fullName>FIAT ARMAZEM</fullName>
            </value>
            <value>
                <fullName>FORD ARMAZEM CAJAMAR</fullName>
            </value>
            <value>
                <fullName>FORD ARMAZEM SP BARUERI</fullName>
            </value>
            <value>
                <fullName>GM ARMAZEM DSH</fullName>
            </value>
            <value>
                <fullName>HONDA REPOSICAO</fullName>
            </value>
            <value>
                <fullName>MITSUBISHI ARMAZEM</fullName>
            </value>
            <value>
                <fullName>NISSAN ARMAZEM</fullName>
            </value>
            <value>
                <fullName>PEUGEOT ARMAZEM</fullName>
            </value>
            <value>
                <fullName>RENAULT ARMAZEM</fullName>
            </value>
            <value>
                <fullName>TOYOTA ARMAZEM</fullName>
            </value>
            <value>
                <fullName>TOYOTA ARMAZEM ARGENTINA</fullName>
            </value>
            <value>
                <fullName>TOYOTA TSUSHO</fullName>
            </value>
            <value>
                <fullName>VOLKSWAGEN ARMAZEM</fullName>
            </value>
            <value>
                <fullName>FIAT ARGENTINA</fullName>
            </value>
            <value>
                <fullName>FIAT ASIA</fullName>
            </value>
            <value>
                <fullName>FIAT/PEUGEOT URUGUAI</fullName>
            </value>
            <value>
                <fullName>FORD ALEMANHA</fullName>
            </value>
            <value>
                <fullName>FORD AMERICA LATINA</fullName>
            </value>
            <value>
                <fullName>FORD ARGENTINA</fullName>
            </value>
            <value>
                <fullName>FORD CHILE</fullName>
            </value>
            <value>
                <fullName>FORD INDIA</fullName>
            </value>
            <value>
                <fullName>FORD MEXICO</fullName>
            </value>
            <value>
                <fullName>FORD PERU</fullName>
            </value>
            <value>
                <fullName>GM AMERICA LATINA</fullName>
            </value>
            <value>
                <fullName>GM ARGENTINA</fullName>
            </value>
            <value>
                <fullName>GM CHILE</fullName>
            </value>
            <value>
                <fullName>GM EQUADOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cod_Canal__c.field-meta.xml
<CustomField>
    <fullName>Cod_Canal__c</fullName>
    <description>Código do Canal</description>
    <label>Cod Canal</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>901</fullName>
            </value>
            <value>
                <fullName>905</fullName>
            </value>
            <value>
                <fullName>907</fullName>
            </value>
            <value>
                <fullName>908</fullName>
            </value>
            <value>
                <fullName>909</fullName>
            </value>
            <value>
                <fullName>910</fullName>
            </value>
            <value>
                <fullName>911</fullName>
            </value>
            <value>
                <fullName>912</fullName>
            </value>
            <value>
                <fullName>915</fullName>
            </value>
            <value>
                <fullName>916</fullName>
            </value>
            <value>
                <fullName>920</fullName>
            </value>
            <value>
                <fullName>921</fullName>
            </value>
            <value>
                <fullName>922</fullName>
            </value>
            <value>
                <fullName>929</fullName>
            </value>
            <value>
                <fullName>930</fullName>
            </value>
            <value>
                <fullName>931</fullName>
            </value>
            <value>
                <fullName>932</fullName>
            </value>
            <value>
                <fullName>933</fullName>
            </value>
            <value>
                <fullName>934</fullName>
            </value>
            <value>
                <fullName>935</fullName>
            </value>
            <value>
                <fullName>936</fullName>
            </value>
            <value>
                <fullName>938</fullName>
            </value>
            <value>
                <fullName>939</fullName>
            </value>
            <value>
                <fullName>940</fullName>
            </value>
            <value>
                <fullName>941</fullName>
            </value>
            <value>
                <fullName>942</fullName>
            </value>
            <value>
                <fullName>943</fullName>
            </value>
            <value>
                <fullName>944</fullName>
            </value>
            <value>
                <fullName>945</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Condicoes_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicoes_de_Pagamento__c</fullName>
    <inlineHelpText>Indique qual seria a condição de pagamento preferencial do cliente.</inlineHelpText>
    <label>Condições de Pagamento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apresentação</fullName>
            </value>
            <value>
                <fullName>Antecipado 7DD</fullName>
            </value>
            <value>
                <fullName>À vista 21DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 1x 30 DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 2x 20/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 3x 20/30/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 4x 20/25/35/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 5x 20/25/30/35/40DD</fullName>
            </value>
            <value>
                <fullName>45 dias em 2x (30/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 3x (30/45/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 4x (30/40/50/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 5x (25/35/45/55/65DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 3x (30/60/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 4x (30/50/70/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 5x (30/45/60/75/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 7x (30/40/50/60/70/80/90DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 3x (30/75/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 4x (30/60/90/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 5x (30/55/75/95/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 7x (30/45/60/75/90/105/120DD)</fullName>
            </value>
            <value>
                <fullName>30 dias</fullName>
                <isActive>false</isActive>
                <label>30 dias</label>
            </value>
            <value>
                <fullName>45 dias</fullName>
                <isActive>false</isActive>
                <label>45 dias</label>
            </value>
            <value>
                <fullName>60 dias</fullName>
                <isActive>false</isActive>
                <label>60 dias</label>
            </value>
            <value>
                <fullName>75 dias</fullName>
                <isActive>false</isActive>
                <label>75 dias</label>
            </value>
            <value>
                <fullName>teste</fullName>
                <isActive>false</isActive>
                <label>teste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/email_comercial__c.field-meta.xml
<CustomField>
    <fullName>email_comercial__c</fullName>
    <label>Email comercial</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/email_DANFE_xml__c.field-meta.xml
<CustomField>
    <fullName>email_DANFE_xml__c</fullName>
    <inlineHelpText>Caso você deseje que seu cliente receba uma cópia da Nota Fiscal, preencha esse campo. Pode ser o mesmo email do comercial.</inlineHelpText>
    <label>Email DANFE xml</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/MunicipalRegistration__c.field-meta.xml
<CustomField>
    <fullName>MunicipalRegistration__c</fullName>
    <label>Inscrição Municipal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NomeAbreviado__c.field-meta.xml
<CustomField>
    <fullName>NomeAbreviado__c</fullName>
    <label>Nome Abreviado</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ramo_de_Atividade__c.field-meta.xml
<CustomField>
    <fullName>Ramo_de_Atividade__c</fullName>
    <inlineHelpText>Lojista: negócio B2C, voltado a vender e instalar acessórios para o consumidor final.
Distribuidor: é um negócio B2B, voltado a atender as lojas multimarcas do setor, faz compras de grandes volumes e não atende consumidor final.
Autorizada: revenda de veículos autorizada pela montadora que também vende acessórios.
E-commerce: negócio B2C, voltado a vender acessórios para o consumidor final pela internet.</inlineHelpText>
    <label>Ramo de Atividade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lojista</fullName>
            </value>
            <value>
                <fullName>Distribuidor</fullName>
            </value>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>Razão Social</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercado__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>After Nacional</fullName>
            </value>
            <value>
                <fullName>After Export</fullName>
            </value>
            <value>
                <fullName>Armazém</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>P&amp;A</fullName>
            </value>
            <value>
                <fullName>Mod Center</fullName>
            </value>
            <value>
                <fullName>Montadora Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Telefone_fixo__c.field-meta.xml
<CustomField>
    <fullName>Telefone_fixo__c</fullName>
    <label>Telefone fixo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Varejo.recordType-meta.xml
<RecordType>
    <fullName>Varejo</fullName>
    <active>true</active>
    <label>Varejo</label>
</RecordType>

force-app/main/default/classes/TOTVSQOPServiceTest.cls
@isTest
private class TOTVSQOPServiceTest {

    @TestSetup
    static void makeData(){
        Account account = new Account(
            NomeAbreviado__c = 'T1234',
            Name = 'L-Teste',
            Phone = '+55(11)98765-4321',
            Neighborhood__c = 'Bairro Teste',
            MunicipalRegistration__c = '123456789',
            RazaoSocial__c = 'Razao Social Teste',
            email_comercial__c = 'teste@teste.com',
            BillingStreet = 'Rua Teste, 152',
            BillingCity = 'Cidade Teste',
            BillingState = 'SP',
            BillingPostalCode = '12345-678',
            BillingCountry = 'BRASIL',
            Telefone_fixo__c = '+55(11)98765-4321',
            Ramo_de_Atividade__c = 'Lojista',
            email_DANFE_xml__c = 'danfe@teste.com',
            Bandeira__c = 'KEKO',
            Cod_Canal__c = '2',
            Canal__c = 'AFTER MI',
            Segmento__c = 'After Nacional',
            Condicoes_de_Pagamento__c = 'Apresentação',
            CNPJ__c = '12345678000195',
            Mercado__c = 'Varejo',
            Compra_mensal_pretendida_na_abertura_da__c = 2000,
            Nome_do_contato_principal__c = 'Contato principal',
            Valor_pretendido_do_primeiro_pedido__c = 250,
            email_financeiro__c = 'teste@teste.com'
        );

        insert account;

        Opportunity opportunity = new Opportunity(
            Name = 'Oportunidade Teste',
            StageName = 'Teste',
            CloseDate = Date.today(),
            AccountId = account.Id
        );

        insert opportunity;

        Product2 product = new Product2(
            Name = 'Produto Teste',
            ProductCode = 'P001',
            IsActive = true
        );

        insert product;

        Id standardPricebookId = Test.getStandardPricebookId();
    
        PricebookEntry standardEntry = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = product.Id,
            UnitPrice = 50,
            IsActive = true
        );

        insert standardEntry;

        Pricebook2 customPricebook = new Pricebook2(
            Name = 'Tabela Teste',
            PriceBookCode__c = '0022412B',
            IsActive = true
        );

        insert customPricebook;

        PricebookEntry customEntry = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = product.Id,
            UnitPrice = 50,
            IsActive = true
        );

        insert customEntry;

        Quote quote = new Quote(
            Name = 'Cotação Teste',
            Pricebook2Id = customPricebook.Id,
            CondicoesPagamento__c = 'Apresentação',
            OpportunityId = opportunity.Id
        );

        insert quote;
        
        QuoteLineItem item = new QuoteLineItem(
            QuoteId = quote.Id,
            PricebookEntryId = customEntry.Id,
            Quantity = 1,
            UnitPrice = 50
        );

        insert item;
    }

    private class TOTVSQOPMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{ "success": true, "message": "OK" }');
            res.setStatusCode(200);
            return res;
        }
    }


    @isTest
    static void testSendQuote() {

        Quote quote = [SELECT Id FROM Quote LIMIT 1];

        Test.setMock(HttpCalloutMock.class, new TOTVSQOPMock());

        Test.startTest();
        TOTVSQOPService.sendQuote(quote.Id);
        Test.stopTest();

        List<Integration_Log__c> logs = [SELECT Id FROM Integration_Log__c WHERE Quote__c = :quote.Id];
        System.assertEquals(0, logs.size(), 'Não deve ter log de erro.');
    }

    @isTest
    static void testSimulateQuote() {
        TOTVSQuoteDTO dto = new TOTVSQuoteDTO();
        dto.branchId = '20';
        dto.cifCity = 'Destino';
        dto.codeCarrier = 92;
        dto.customerCoder = 569;
        dto.deliveryCode = 'Padrão';
        dto.customerDiscount = 10;
        dto.paymentTerms = 130;
        dto.percentageFreight = 0;
        dto.priceTableQuote = '0022412B';
        dto.salesChannel = 2;
        dto.operationTypeCode = 1;
        dto.priceQuoteType = 2;
        dto.useDiscountTable = true;
        dto.shortName = 'Auto K';
        dto.transactionType = '511021';
        dto.valueFreight = 0;
        dto.addItem('P001', '0022412', 1);

        Test.setMock(HttpCalloutMock.class, new TOTVSQOPMock());

        Test.startTest();
        String result = TOTVSQOPService.simulateQuote(dto);
        Test.stopTest();

        System.assert(result.contains('success'), 'Resposta deve conter sucesso');
    }
}