force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Condicoes_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicoes_de_Pagamento__c</fullName>
    <inlineHelpText>Indique qual seria a condição de pagamento preferencial do cliente.</inlineHelpText>
    <label>Condições de Pagamento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apresentação</fullName>
            </value>
            <value>
                <fullName>Antecipado 7DD</fullName>
            </value>
            <value>
                <fullName>À vista 21DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 1x 30 DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 2x 20/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 3x 20/30/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 4x 20/25/35/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 5x 20/25/30/35/40DD</fullName>
            </value>
            <value>
                <fullName>45 dias em 2x (30/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 3x (30/45/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 4x (30/40/50/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 5x (25/35/45/55/65DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 3x (30/60/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 4x (30/50/70/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 5x (30/45/60/75/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 7x (30/40/50/60/70/80/90DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 3x (30/75/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 4x (30/60/90/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 5x (30/55/75/95/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 7x (30/45/60/75/90/105/120DD)</fullName>
            </value>
            <value>
                <fullName>30 dias</fullName>
                <isActive>false</isActive>
                <label>30 dias</label>
            </value>
            <value>
                <fullName>45 dias</fullName>
                <isActive>false</isActive>
                <label>45 dias</label>
            </value>
            <value>
                <fullName>60 dias</fullName>
                <isActive>false</isActive>
                <label>60 dias</label>
            </value>
            <value>
                <fullName>75 dias</fullName>
                <isActive>false</isActive>
                <label>75 dias</label>
            </value>
            <value>
                <fullName>teste</fullName>
                <isActive>false</isActive>
                <label>teste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/email_comercial__c.field-meta.xml
<CustomField>
    <fullName>email_comercial__c</fullName>
    <label>Email comercial</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Varejo</fullName>
            </value>
            <value>
                <fullName>Montadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ramo_de_Atividade__c.field-meta.xml
<CustomField>
    <fullName>Ramo_de_Atividade__c</fullName>
    <inlineHelpText>Lojista: negócio B2C, voltado a vender e instalar acessórios para o consumidor final.
Distribuidor: é um negócio B2B, voltado a atender as lojas multimarcas do setor, faz compras de grandes volumes e não atende consumidor final.
Autorizada: revenda de veículos autorizada pela montadora que também vende acessórios.
E-commerce: negócio B2C, voltado a vender acessórios para o consumidor final pela internet.</inlineHelpText>
    <label>Ramo de Atividade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lojista</fullName>
            </value>
            <value>
                <fullName>Distribuidor</fullName>
            </value>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>Razão Social</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercado__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>After Nacional</fullName>
            </value>
            <value>
                <fullName>After Export</fullName>
            </value>
            <value>
                <fullName>Armazém</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>P&amp;A</fullName>
            </value>
            <value>
                <fullName>Mod Center</fullName>
            </value>
            <value>
                <fullName>Montadora Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Varejo.recordType-meta.xml
<RecordType>
    <fullName>Varejo</fullName>
    <active>true</active>
    <label>Varejo</label>
</RecordType>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Condicoes_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicoes_de_Pagamento__c</fullName>
    <inlineHelpText>indique qual seria a condição de pagamento preferencial do cliente</inlineHelpText>
    <label>Condições de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apresentação</fullName>
            </value>
            <value>
                <fullName>Antecipado 7DD</fullName>
            </value>
            <value>
                <fullName>À vista 21DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 1x 30 DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 2x 20/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 3x 20/30/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 4x 20/25/35/40DD</fullName>
            </value>
            <value>
                <fullName>30 dias em 5x 20/25/30/35/40DD</fullName>
            </value>
            <value>
                <fullName>45 dias em 2x (30/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 3x (30/45/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 4x (30/40/50/60DD)</fullName>
            </value>
            <value>
                <fullName>45 dias em 5x (25/35/45/55/65DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 3x (30/60/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 4x (30/50/70/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 5x (30/45/60/75/90DD)</fullName>
            </value>
            <value>
                <fullName>60 dias em 7x (30/40/50/60/70/80/90DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 3x (30/75/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 4x (30/60/90/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 5x (30/55/75/95/120DD)</fullName>
            </value>
            <value>
                <fullName>75 dias em 7x (30/45/60/75/90/105/120DD)</fullName>
            </value>
            <value>
                <fullName>30 dias</fullName>
                <isActive>false</isActive>
                <label>30 dias</label>
            </value>
            <value>
                <fullName>45 dias</fullName>
                <isActive>false</isActive>
                <label>45 dias</label>
            </value>
            <value>
                <fullName>60 dias</fullName>
                <isActive>false</isActive>
                <label>60 dias</label>
            </value>
            <value>
                <fullName>75 dias</fullName>
                <isActive>false</isActive>
                <label>75 dias</label>
            </value>
            <value>
                <fullName>teste</fullName>
                <isActive>false</isActive>
                <label>teste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/email_comercial__c.field-meta.xml
<CustomField>
    <fullName>email_comercial__c</fullName>
    <label>Email comercial</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Ramo_de_Atividade__c.field-meta.xml
<CustomField>
    <fullName>Ramo_de_Atividade__c</fullName>
    <inlineHelpText>Lojista: negócio B2C, voltado a vender e instalar acessórios para o consumidor final.
Distribuidor: é um negócio B2B, voltado a atender as lojas multimarcas do setor, faz compras de grandes volumes e não atende consumidor final.
Autorizada: revenda de veículos autorizada pela montadora que também vende acessórios.
E-commerce: negócio B2C, voltado a vender acessórios para o consumidor final pela internet.</inlineHelpText>
    <label>Ramo de Atividade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lojista</fullName>
            </value>
            <value>
                <fullName>Distribuidor</fullName>
            </value>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>RazaoSocial</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>After Nacional</fullName>
            </value>
            <value>
                <fullName>After Export</fullName>
            </value>
            <value>
                <fullName>Armazém</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>P&amp;A</fullName>
            </value>
            <value>
                <fullName>Mod Center</fullName>
            </value>
            <value>
                <fullName>Montadora Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Varejo.recordType-meta.xml
<RecordType>
    <fullName>Varejo</fullName>
    <active>true</active>
    <businessProcess>Varejo</businessProcess>
    <label>Varejo</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Varejo</fullName>
            </value>
            <value>
                <fullName>Montadora</fullName>
            </value>
            <value>
                <fullName>E-commerce B2B</fullName>
            </value>
            <value>
                <fullName>E-commerce B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountUtils.cls
public with sharing class AccountUtils {

    //AccountUtils.createAccount();

    public static void createAccount() {

        Account newAccount = new Account();

        List<String> streets = new List<String>{'Rua das Flores', 'Avenida Paulista', 'Rua dos Alfeneiros', 'Avenida Atlântica', 'Rua Augusta'};
        List<String> cities = new List<String>{'São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba', 'Porto Alegre'};
        List<String> states = new List<String>{'SP', 'RJ', 'MG', 'PR', 'RS'};
        List<String> neighborhoods = new List<String>{'Centro', 'Bela Vista', 'Copacabana', 'Savassi', 'Jardim Botânico'};
        
        String baseCNPJ = generateRandomCNPJ();
        String postalCode = String.valueOf(Math.mod(Math.abs(Crypto.getRandomInteger()), 100000));
        String phone = generateRandomPhone();
        String uniqueId = String.valueOf(Math.abs(Crypto.getRandomLong()));
        String street = streets[Math.mod(Math.abs(Crypto.getRandomInteger()), streets.size())];
        String city = cities[Math.mod(Math.abs(Crypto.getRandomInteger()), cities.size())];
        String state = states[Math.mod(Math.abs(Crypto.getRandomInteger()), states.size())];
        String neighborhood = neighborhoods[Math.mod(Math.abs(Crypto.getRandomInteger()), neighborhoods.size())];
        String streetNumber = String.valueOf(Math.mod(Math.abs(Crypto.getRandomInteger()), 1000));
        String recordtypeId =  [SELECT Id FROM RecordType WHERE DeveloperName = 'Varejo' AND SObjectType = 'Account' LIMIT 1].Id;
        String name = getNextAccountName();

        newAccount.Name = name;
        newAccount.RazaoSocial__c = name; 
        newAccount.CNPJ__c = baseCNPJ; 
        newAccount.Email_Comercial__c = uniqueId + '@test.com'; 
        newAccount.BillingStreet = street + ', '+streetNumber; 
        newAccount.BillingStreet = street + ', ' + streetNumber + ', Casa';  
        newAccount.BillingCity = city; 
        newAccount.BillingState = state;  
        newAccount.BillingCountry = 'BRASIL'; 
        newAccount.BillingPostalCode = postalCode; 
        newAccount.Phone = phone;
        newAccount.Ramo_de_Atividade__c = 'Lojista';
        newAccount.Neighborhood__c = neighborhood;
        newAccount.Mercado__c = 'Varejo';
        newAccount.RecordTypeId = recordtypeId;
        newAccount.Segmento__c = 'After Nacional';
        newAccount.Condicoes_de_Pagamento__c = '30 dias';
        newAccount.codigoCondicaoPagamento__c = '130';
        
        try {
            insert newAccount;
            System.debug('Conta criada com sucesso: ' + newAccount.Id);
        } catch (Exception e) {
            System.debug('Erro ao criar conta: ' + e.getMessage());
        }
    }

    public static String generateRandomCNPJ() {
        String baseCNPJ = '';
        for (Integer i = 0; i < 12; i++) {
            baseCNPJ += String.valueOf(Math.mod(Math.abs(Crypto.getRandomInteger()), 10));
        }
        Integer[] weights1 = new Integer[] {5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2};
            Integer[] weights2 = new Integer[] {6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2};
                
                Integer sum1 = 0;
        for (Integer i = 0; i < weights1.size(); i++) {
            sum1 += Integer.valueOf(baseCNPJ.substring(i, i + 1)) * weights1[i];
        }
        
        Integer mod1 = Math.mod(sum1, 11);
        Integer firstDigit = (mod1 < 2) ? 0 : 11 - mod1;
        baseCNPJ += String.valueOf(firstDigit);
        
        Integer sum2 = 0;
        for (Integer i = 0; i < weights2.size(); i++) {
            sum2 += Integer.valueOf(baseCNPJ.substring(i, i + 1)) * weights2[i];
        }
        
        Integer mod2 = Math.mod(sum2, 11);
        Integer secondDigit = (mod2 < 2) ? 0 : 11 - mod2;
        return baseCNPJ + String.valueOf(secondDigit);
    }

    public static String generateRandomPhone() {

        String prefix = '+55319';
        String randomDigits = '';
        
        for (Integer i = 0; i < 8; i++) {
            Integer randomDigit = Math.floor(Math.random() * 10).intValue(); 
            randomDigits += String.valueOf(randomDigit);
        }
        
        return prefix + randomDigits;
    }

    public static String getNextAccountName() {

        String baseName = '<<Teste>> ';

        List<Account> accounts = [SELECT Id, Name 
                                  FROM Account 
                                  WHERE Name LIKE '%<<Teste>> %' 
                                  ORDER BY CreatedDate DESC 
                                  LIMIT 1];
        
        String lastName;
        if (!accounts.isEmpty()) {
            lastName = accounts[0].Name;
        } else {
            lastName = null;
        }
        
        Integer currentNumber = 0;
        if (lastName != null && lastName.startsWith(baseName)) {
            String numberPart = lastName.replace(baseName, '');
            try {
                currentNumber = Integer.valueOf(numberPart);
            } catch (Exception e) {
                System.debug('Erro ao converter o número: ' + e.getMessage());
            }
        }
        
        Integer nextNumber = currentNumber + 1;
        
        String nextNumberFormatted = String.valueOf(nextNumber);
        
        while (nextNumberFormatted.length() < 4) {
            nextNumberFormatted = '0' + nextNumberFormatted;
        }
        
        System.debug(baseName + nextNumberFormatted);
        return baseName + nextNumberFormatted;
    }

    public static void deleteTestRecordsCreatedToday() {

        Date today = Date.today();
        
        List<Account> accountsToDelete = [SELECT Id FROM Account WHERE CreatedDate = TODAY AND Name like '%<<Teste>>%'];
        
        List<Contact> contactsToDelete = [SELECT Id FROM Contact WHERE CreatedDate = TODAY AND Name like '%<<Teste>>%'];
        
        List<Opportunity> opportunitiesToDelete = [SELECT Id FROM Opportunity WHERE CreatedDate = TODAY AND Name like '%<<Teste>>%'];
        
        List<Lead> leadsToDelete = [SELECT Id FROM Lead WHERE CreatedDate = TODAY AND Name like '%<<Teste>>%'];

        if (!opportunitiesToDelete.isEmpty()) {
            delete opportunitiesToDelete;
        }

        if (!contactsToDelete.isEmpty()) {
            delete contactsToDelete;
        } 

        if (!accountsToDelete.isEmpty()) {
            delete accountsToDelete;
        }

        if (!leadsToDelete.isEmpty()) {
            delete leadsToDelete;
        } 
    }
}