force-app/main/default/objects/Account/fields/email_comercial__c.field-meta.xml
<CustomField>
    <fullName>email_comercial__c</fullName>
    <label>Email comercial</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/email_DANFE_xml__c.field-meta.xml
<CustomField>
    <fullName>email_DANFE_xml__c</fullName>
    <inlineHelpText>Caso você deseje que seu cliente receba uma cópia da Nota Fiscal, preencha esse campo. Pode ser o mesmo email do comercial.</inlineHelpText>
    <label>Email DANFE xml</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/MunicipalRegistration__c.field-meta.xml
<CustomField>
    <fullName>MunicipalRegistration__c</fullName>
    <label>Inscrição Municipal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ramo_de_Atividade__c.field-meta.xml
<CustomField>
    <fullName>Ramo_de_Atividade__c</fullName>
    <inlineHelpText>Lojista: negócio B2C, voltado a vender e instalar acessórios para o consumidor final.
Distribuidor: é um negócio B2B, voltado a atender as lojas multimarcas do setor, faz compras de grandes volumes e não atende consumidor final.
Autorizada: revenda de veículos autorizada pela montadora que também vende acessórios.
E-commerce: negócio B2C, voltado a vender acessórios para o consumidor final pela internet.</inlineHelpText>
    <label>Ramo de Atividade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lojista</fullName>
            </value>
            <value>
                <fullName>Distribuidor</fullName>
            </value>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>Razão Social</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Telefone_fixo__c.field-meta.xml
<CustomField>
    <fullName>Telefone_fixo__c</fullName>
    <label>Telefone fixo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountSelectorTest.cls
@isTest
private class AccountSelectorTest {

    @TestSetup
    static void createData() {
        Account testAccount = new Account(
            Name = 'Conta de Teste',
            Phone = '+55(11)98765-4321',
            Neighborhood__c = 'Bairro Teste',
            MunicipalRegistration__c = '123456789',
            RazaoSocial__c = 'Razao Social Teste',
            email_comercial__c = 'teste@teste.com',
            BillingStreet = 'Rua Teste',
            BillingCity = 'Cidade Teste',
            BillingState = 'Estado Teste',
            BillingPostalCode = '12345-678',
            BillingCountry = 'País Teste',
            Telefone_fixo__c = '+55(11)98765-4321',
            Ramo_de_Atividade__c = 'Lojista',
            email_DANFE_xml__c = 'danfe@teste.com'
        );
        insert testAccount;
    }

    @isTest
    static void testTotvsMapper() {
        Test.startTest();

        Account testAccount = [SELECT Id FROM Account LIMIT 1];

        Account result = AccountSelector.selectAccountById(testAccount.Id);

        System.assertNotEquals(null, result, 'A conta não deve ser nula');
        System.assertEquals(testAccount.Id, result.Id, 'O ID da conta retornada deve ser igual ao ID da conta criada');
        System.assertEquals('Conta de Teste', result.Name, 'O nome da conta deve ser "Conta de Teste"');
        System.assertEquals('+55(11)98765-4321', result.Phone, 'O telefone da conta deve ser "+55(11)98765-4321"');
        System.assertEquals('Bairro Teste', result.Neighborhood__c, 'O bairro da conta deve ser "Bairro Teste"');
        System.assertEquals('123456789', result.MunicipalRegistration__c, 'A inscrição municipal deve ser "123456789"');
        System.assertEquals('Razao Social Teste', result.RazaoSocial__c, 'A razão social deve ser "Razao Social Teste"');
        System.assertEquals('teste@teste.com', result.email_comercial__c, 'O email comercial deve ser "teste@teste.com"');
        System.assertEquals('Rua Teste', result.BillingStreet, 'A rua de cobrança deve ser "Rua Teste"');
        System.assertEquals('Cidade Teste', result.BillingCity, 'A cidade de cobrança deve ser "Cidade Teste"');
        System.assertEquals('Estado Teste', result.BillingState, 'O estado de cobrança deve ser "Estado Teste"');
        System.assertEquals('12345-678', result.BillingPostalCode, 'O código postal de cobrança deve ser "12345-678"');
        System.assertEquals('País Teste', result.BillingCountry, 'O país de cobrança deve ser "País Teste"');
        System.assertEquals('+55(11)98765-4321', result.Telefone_fixo__c, 'O telefone fixo deve ser "+55(11)98765-4321"');
        System.assertEquals('Lojista', result.Ramo_de_Atividade__c, 'O ramo de atividade deve ser "Lojista"');
        System.assertEquals('danfe@teste.com', result.email_DANFE_xml__c, 'O email para DANFE/XML deve ser "danfe@teste.com"');

        Test.stopTest();
    }
}