force-app/main/default/objects/Lead/fields/Bandeira__c.field-meta.xml
<CustomField>
    <fullName>Bandeira__c</fullName>
    <label>Bandeira</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cod_Canal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KEKO</fullName>
            </value>
            <value>
                <fullName>FIAT</fullName>
            </value>
            <value>
                <fullName>HYUNDAI</fullName>
            </value>
            <value>
                <fullName>FORD</fullName>
            </value>
            <value>
                <fullName>RENAULT</fullName>
            </value>
            <value>
                <fullName>PEUGEOT</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>HONDA</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>VOLKS</fullName>
            </value>
            <value>
                <fullName>NISSAN</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MERCEDES</fullName>
            </value>
            <value>
                <fullName>JEEP/RAM</fullName>
            </value>
            <value>
                <fullName>AGRALE</fullName>
                <isActive>false</isActive>
                <label>AGRALE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segmento__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AFTER ME</fullName>
            </value>
            <value>
                <fullName>KEKO USA</fullName>
            </value>
            <value>
                <fullName>AFTER MI</fullName>
            </value>
            <value>
                <fullName>FIAT ARMAZEM</fullName>
            </value>
            <value>
                <fullName>FORD ARMAZEM CAJAMAR</fullName>
            </value>
            <value>
                <fullName>FORD ARMAZEM SP BARUERI</fullName>
            </value>
            <value>
                <fullName>GM ARMAZEM DSH</fullName>
            </value>
            <value>
                <fullName>HONDA REPOSICAO</fullName>
            </value>
            <value>
                <fullName>MITSUBISHI ARMAZEM</fullName>
            </value>
            <value>
                <fullName>NISSAN ARMAZEM</fullName>
            </value>
            <value>
                <fullName>PEUGEOT ARMAZEM</fullName>
            </value>
            <value>
                <fullName>RENAULT ARMAZEM</fullName>
            </value>
            <value>
                <fullName>TOYOTA ARMAZEM</fullName>
            </value>
            <value>
                <fullName>TOYOTA ARMAZEM ARGENTINA</fullName>
            </value>
            <value>
                <fullName>TOYOTA TSUSHO</fullName>
            </value>
            <value>
                <fullName>VOLKSWAGEN ARMAZEM</fullName>
            </value>
            <value>
                <fullName>FIAT ARGENTINA</fullName>
            </value>
            <value>
                <fullName>FIAT ASIA</fullName>
            </value>
            <value>
                <fullName>FIAT/PEUGEOT URUGUAI</fullName>
            </value>
            <value>
                <fullName>FORD ALEMANHA</fullName>
            </value>
            <value>
                <fullName>FORD AMERICA LATINA</fullName>
            </value>
            <value>
                <fullName>FORD ARGENTINA</fullName>
            </value>
            <value>
                <fullName>FORD CHILE</fullName>
            </value>
            <value>
                <fullName>FORD INDIA</fullName>
            </value>
            <value>
                <fullName>FORD MEXICO</fullName>
            </value>
            <value>
                <fullName>FORD PERU</fullName>
            </value>
            <value>
                <fullName>GM AMERICA LATINA</fullName>
            </value>
            <value>
                <fullName>GM ARGENTINA</fullName>
            </value>
            <value>
                <fullName>GM CHILE</fullName>
            </value>
            <value>
                <fullName>GM EQUADOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade da Mesorregião</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Cod_Canal__c.field-meta.xml
<CustomField>
    <fullName>Cod_Canal__c</fullName>
    <description>Código do Canal</description>
    <label>Cod Canal</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>901</fullName>
            </value>
            <value>
                <fullName>905</fullName>
            </value>
            <value>
                <fullName>907</fullName>
            </value>
            <value>
                <fullName>908</fullName>
            </value>
            <value>
                <fullName>909</fullName>
            </value>
            <value>
                <fullName>910</fullName>
            </value>
            <value>
                <fullName>911</fullName>
            </value>
            <value>
                <fullName>912</fullName>
            </value>
            <value>
                <fullName>915</fullName>
            </value>
            <value>
                <fullName>916</fullName>
            </value>
            <value>
                <fullName>920</fullName>
            </value>
            <value>
                <fullName>921</fullName>
            </value>
            <value>
                <fullName>922</fullName>
            </value>
            <value>
                <fullName>929</fullName>
            </value>
            <value>
                <fullName>930</fullName>
            </value>
            <value>
                <fullName>931</fullName>
            </value>
            <value>
                <fullName>932</fullName>
            </value>
            <value>
                <fullName>933</fullName>
            </value>
            <value>
                <fullName>934</fullName>
            </value>
            <value>
                <fullName>935</fullName>
            </value>
            <value>
                <fullName>936</fullName>
            </value>
            <value>
                <fullName>938</fullName>
            </value>
            <value>
                <fullName>939</fullName>
            </value>
            <value>
                <fullName>940</fullName>
            </value>
            <value>
                <fullName>941</fullName>
            </value>
            <value>
                <fullName>942</fullName>
            </value>
            <value>
                <fullName>943</fullName>
            </value>
            <value>
                <fullName>944</fullName>
            </value>
            <value>
                <fullName>945</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/email_comercial__c.field-meta.xml
<CustomField>
    <fullName>email_comercial__c</fullName>
    <label>Email comercial</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Ramo_de_Atividade__c.field-meta.xml
<CustomField>
    <fullName>Ramo_de_Atividade__c</fullName>
    <inlineHelpText>Lojista: negócio B2C, voltado a vender e instalar acessórios para o consumidor final.
Distribuidor: é um negócio B2B, voltado a atender as lojas multimarcas do setor, faz compras de grandes volumes e não atende consumidor final.
Autorizada: revenda de veículos autorizada pela montadora que também vende acessórios.
E-commerce: negócio B2C, voltado a vender acessórios para o consumidor final pela internet.</inlineHelpText>
    <label>Ramo de Atividade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lojista</fullName>
            </value>
            <value>
                <fullName>Distribuidor</fullName>
            </value>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>After Nacional</fullName>
            </value>
            <value>
                <fullName>After Export</fullName>
            </value>
            <value>
                <fullName>Armazém</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>P&amp;A</fullName>
            </value>
            <value>
                <fullName>Mod Center</fullName>
            </value>
            <value>
                <fullName>Montadora Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefone_fixo__c.field-meta.xml
<CustomField>
    <fullName>Telefone_fixo__c</fullName>
    <label>Telefone fixo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Varejo.recordType-meta.xml
<RecordType>
    <fullName>Varejo</fullName>
    <active>true</active>
    <businessProcess>Varejo</businessProcess>
    <label>Varejo</label>
</RecordType>

force-app/main/default/classes/LeadCreator.cls
public with sharing class LeadCreator {
    public static void createLeads(integer amount, Boolean generateInvalidData) {
        List<Lead> newLeads = new List<Lead>();

        List<String> firstNames = new List<String>{'Antônio', 'Roberta', 'Carol', 'Fábio', 'Ricardo', 'Esther', 'Alice', 'Roberto', 'Caio', 'Fernanda', 'Deborah', 'Guilher'};
        List<String> lastNames = new List<String>{'Assunção', 'Costa', 'Souza', 'Britto', 'Moraes', 'Santos', 'Brutapi', 'Moura', 'Santana', 'Braga', 'Santos', 'Braga'};
        

        for(Integer i = 1; i <= amount; i++) {
            String firstName = firstNames[Math.mod(Math.abs(Crypto.getRandomInteger()), firstNames.size())];
            String lastName = lastNames[Math.mod(Math.abs(Crypto.getRandomInteger()), lastNames.size())];
            String numberCompany = String.valueOf(Math.mod(Math.abs(Crypto.getRandomInteger()), 10000));


            Lead lead = new Lead(
                FirstName = firstName,
                LastName = generateInvalidData ? null : lastName,
                Phone = '112345678' + i,
                Segmento__c = 'After Nacional',
                Telefone_fixo__c = '112333333' + i,
                Ramo_de_Atividade__c = 'Lojista',
                email_comercial__c = 'lead'+i+'@email.com',
                LeadSource = 'Site Keko',
                Mercado__c = 'Varejo',
                Company = 'LTDA. ' + numberCompany,
                Canal__c = 'AFTER MI',
                Cod_Canal__c = '2',
                Bandeira__c = 'KEKO',
                Cidade__c = 'a02be000001S99sAAC'
            );

            newleads.add(lead);
        }

        try {
            insert newLeads;
            System.debug('Leads inseridos com sucesso no sistema de desenvolvimento.');
        } catch (DmlException e) {
            for(Integer j = 0; j < e.getNumDml(); j++) {
                System.debug('Erro ao inserir Lead: ' + e.getDmlMessage(j));
            }
        }
        
    }
}